# See: <https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference>
version: 2
updates:
- package-ecosystem: pip
  open-pull-requests-limit: 2
  directories:
  - /
  schedule:
    interval: weekly
  groups:
    python:
      patterns:
      - "*"

- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
  groups:
    actions:
      patterns:
      - "*"

- package-ecosystem: devcontainers
  directory: .devcontainer
  schedule:
    interval: weekly
  groups:
    devcontainer:
      patterns:
      - "*"

- package-ecosystem: docker
  directory: .devcontainer
  schedule:
    interval: weekly
  groups:
    docker:
      patterns:
      - "*"
