# See: <https://docs.codecov.com/docs/codecovyml-reference>

component_management:
  default_rules:
    statuses:
    - type: project
      target: auto

  individual_components:
  - component_id: mypv
    name: "my-PV"
    paths:
    - packages/mypv/*
