[tool.ruff]
line-length = 100

[tool.ruff.lint]
# See: <https://docs.astral.sh/ruff/rules>
select = [
    "A",
    "ANN",
    "ARG",
    "ASYNC",
    "B",
    "BLE",
    "C4",
    "COM",
    "D",
    "DTZ",
    "E",
    "EM",
    "ERA",
    "F",
    "FA",
    "FBT",
    "FLY",
    "FURB",
    "G",
    "I",
    "ICN",
    "INP",
    "ISC",
    "LOG",
    "N",
    "PIE",
    "PL",
    "PT",
    "PTH",
    "PYI",
    "Q",
    "RET",
    "RSE",
    "RUF",
    "S",
    "SIM",
    "SLF",
    "SLOT",
    "T10",
    "T20",
    "TC",
    "TID",
    "TRY",
    "UP",
    "W",
    "YTT",
    # Disabled because they're in preview
    # "CPY",
    # "DOC",
]
ignore = ["COM812"]


[tool.ruff.lint.per-file-ignores]
"**/tests/**" = [
    "D1",      # docstrings are not required in tests
    "FBT001",  # boolean parameters
    "PLR0915", # too many statements
    "PLR2004", # magic numbers are fine in tests
    "S101",    # asserts are fine in tests
]


[tool.ruff.lint.pydocstyle]
convention = "google"
