[project]
name = "mypv"
version = "0.1.0"
description = "MYPV device communication library"
readme = "README.md"
authors = [{ name = "Simon Berger", email = "simon@siku2.io" }]
requires-python = ">=3.13"
dependencies = ["pymodbus>=3.9.2"]


[project.scripts]
mypv = "mypv.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest-asyncio>=0.26.0",
    "pytest-cov>=6.1.1",
    "pytest-emoji>=0.2.0",
    "pytest-md>=0.2.0",
    "pytest>=8.3.5",
    "ruff>=0.11.9",
    "ty>=0.0.0a8",
]
docs = [
    "mkdocs-api-autonav>=0.2.1",
    "mkdocs-material>=9.6.14",
    "mkdocstrings[python]>=0.29.1",
]

[tool.ruff]
extend = "../../pyproject.toml"


[tool.coverage.report]
# See: <https://github.com/nedbat/coveragepy/issues/831>
exclude_also = ["if TYPE_CHECKING:"]
