[project]
name = "mypv"
version = "0.2.0"
description = "my-PV device communication library"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
keywords = ["mypv", "acthor"]
authors = [{ name = "Simon Berger", email = "simon@siku2.io" }]
maintainers = [{ name = "Simon Berger", email = "simon@siku2.io" }]

requires-python = ">=3.13"
dependencies = ["pymodbus>=3.9.2"]

[project.urls]
Documentation = "https://mypv.readthedocs.io"
Repository = "https://github.com/siku2/home-automation-libraries.git"
Issues = "https://github.com/siku2/home-automation-libraries/issues"

[project.scripts]
mypv = "mypv.cli:main"

[project.optional-dependencies]
http = ["httpx>=0.28.1"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest-asyncio>=0.26.0",
    "pytest-cov>=6.1.1",
    "pytest-emoji>=0.2.0",
    "pytest-httpx>=0.35.0",
    "pytest-md>=0.2.0",
    "pytest>=8.3.5",
    "ruff>=0.11.9",
    "ty>=0.0.0a8",
]
docs = [
    "mkdocs-api-autonav>=0.2.1",
    "mkdocs-material>=9.6.14",
    "mkdocstrings[python]>=0.29.1",
]

[tool.ruff]
extend = "../../pyproject.toml"

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"

[tool.coverage.report]
# See: <https://github.com/nedbat/coveragepy/issues/831>
exclude_also = ["if TYPE_CHECKING:"]
