[project]
name = "acthor"
version = "0.1.0"
description = "AC•THOR Python library"
readme = "README.md"
authors = [{ name = "Simon Berger", email = "simon@siku2.io" }]
requires-python = ">=3.13"
dependencies = ["pymodbus>=3.9.2"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = ["pytest>=8.3.5", "ruff>=0.11.9", "ty>=0.0.0a8"]
