# See: <https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions>

name: "Check"

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:


jobs:
  general:
    name: "General checks"
    runs-on: ubuntu-24.04

    permissions:
      contents: read

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    - name: Check typos
      uses: crate-ci/typos@0f0ccba9ed1df83948f0c15026e4f5ccfce46109 # v1.32.0

    - name: Check for tabs
      run: |
        git ls-files -z | while IFS= read -r -d '' file; do
            if grep -I -P '\t' "$file"; then
                echo "::error file=$file::File contains tabs. Please convert them to spaces."
                exit 1
            fi
        done

  python-package:
    name: "Python: ${{ matrix.package }}"
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
        - package: mypv

    permissions:
      id-token: write

    defaults:
      run:
        working-directory: "packages/${{ matrix.package }}"

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    - uses: astral-sh/setup-uv@6b9c6063abd6010835644d4c2e1bef4cf5cd0fca # v6

    - name: "Lint"
      uses: astral-sh/ruff-action@eaf0ecdd668ceea36159ff9d91882c9795d89b49 # v3
      with:
        src: "packages/${{ matrix.package }}"

    - name: "Check formatting"
      uses: astral-sh/ruff-action@eaf0ecdd668ceea36159ff9d91882c9795d89b49 # v3
      with:
        src: "packages/${{ matrix.package }}"
        args: "format --check --diff"

    - name: "Run tests"
      run: |
        codecov_coverage_args=(--cov --cov-branch --cov-report=xml)
        codecov_test_args=(--junitxml=junit.xml -o junit_family=legacy)
        github_report_args=(--md=report.md --emoji)

        uv run pytest "${codecov_coverage_args[@]}" "${codecov_test_args[@]}" "${github_report_args[@]}" || exit

        echo "::group::..."
        final_report_file="$(mktemp)"
        {
          echo "# \`${{ matrix.package }}\` Test Report"
          echo "<details><summary>Click to expand!</summary>"
          tail -n+2 report.md
          echo "</details>"
        } >>"$final_report_file"

        cat "$final_report_file" >>"$GITHUB_STEP_SUMMARY"
        echo "::endgroup::"
        echo
        echo "====================================================================================="
        echo Markdown summaries: "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
        echo "====================================================================================="

    - name: Upload coverage reports to Codecov
      if: ${{ !cancelled() }}
      uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24 # v5
      with:
        fail_ci_if_error: true
        flags: "${{ matrix.package }}"
        use_oidc: true

    - name: Upload test results to Codecov
      if: ${{ !cancelled() }}
      uses: codecov/test-results-action@f2dba722c67b86c6caa034178c6e4d35335f6706 # v1
      with:
        fail_ci_if_error: true
        flags: "${{ matrix.package }}"
        use_oidc: true
