# See: <https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions>

name: "Check"

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:


jobs:
  general:
    name: "General checks"
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: Check typos
      uses: crate-ci/typos@v1.32.0

  python-package:
    name: "Python: ${{ matrix.package }}"
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
        - package: mypv

    permissions:
      id-token: write

    defaults:
      run:
        working-directory: "packages/${{ matrix.package }}"

    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v3

    - name: "Lint"
      uses: astral-sh/ruff-action@v3
      with:
        src: "packages/${{ matrix.package }}"

    - name: "Check formatting"
      uses: astral-sh/ruff-action@v3
      with:
        src: "packages/${{ matrix.package }}"
        args: "format --check --diff"

    - name: "Run tests"
      run: |
        codecov_coverage_args=(--cov --cov-branch --cov-report=xml)
        codecov_test_args=(--junitxml=junit.xml -o junit_family=legacy)
        github_report_args=(--md=report.md --emoji)

        uv run pytest "${codecov_coverage_args[@]}" "${codecov_test_args[@]}" "${github_report_args[@]}"

        echo "::group::..."
        final_report_file="$(mktemp)"
        {
          echo "# \`${{ matrix.package }}\` Test Report"
          echo "<details><summary>Click to expand!</summary>"
          tail -n+2 report.md
          echo "</details>"
        } >>"$final_report_file"

        cat "$final_report_file" >>"$GITHUB_STEP_SUMMARY"
        echo "::endgroup::"
        echo
        echo "====================================================================================="
        echo Markdown summaries: "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
        echo "====================================================================================="

    - name: Upload coverage reports to Codecov
      if: ${{ !cancelled() }}
      uses: codecov/codecov-action@v5
      with:
        flags: "${{ matrix.package}}"
        use_oidc: true

    - name: Upload test results to Codecov
      if: ${{ !cancelled() }}
      uses: codecov/test-results-action@v1
      with:
        flags: "${{ matrix.package}}"
        use_oidc: true
