# See: <https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions>

name: Create release

on:
  workflow_dispatch:
    inputs:
      package:
        description: "Package"
        required: true
        type: choice
        options:
        - mypv

      version_bump:
        description: "Version to bump"
        required: true
        type: choice
        default: "minor"
        options:
        - patch
        - minor
        - major

      dry_run:
        description: "Dry run"
        required: false
        type: boolean
        default: false

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-24.04

    permissions:
      contents: write

    defaults:
      run:
        working-directory: "packages/${{ inputs.package }}"

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        fetch-depth: 0
    - uses: astral-sh/setup-uv@caf0cab7a618c569241d31dcd442f54681755d39 # v3

    - name: Bump version
      id: version
      run: |
        old_version=$(uv version --short) || exit
        uv version --bump '${{ inputs.version_bump }}' || exit
        version=$(uv version --short) || exit
        {
          echo "old_version=$old_version"
          echo "version=$version"
          echo "old_tag_name=${{ inputs.package }}-$old_version"
          echo "tag_name=${{ inputs.package }}-$version"
        } | tee -a "$GITHUB_OUTPUT"

    - name: Generate a changelog
      id: changelog
      uses: orhun/git-cliff-action@b946ed27a675d653b308f29a7bbad813b85bf7aa # v3
      with:
        args: |
          --verbose \
          --config github \
          --include-path 'packages/${{ inputs.package }}/**/*' \
          --tag "${{ steps.version.outputs.tag_name }}" \
          "${{ steps.version.outputs.old_tag_name }}.."

    - if: ${{ ! inputs.dry_run }}
      name: Commit version
      id: commit
      uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9
      with:
        push: true

    - if: ${{ ! inputs.dry_run }}
      name: Create release
      uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631 # v2
      with:
        body_path: ${{ steps.changelog.outputs.changelog }}
        draft: true
        tag_name: "${{ steps.version.outputs.tag_name }}"
        target_commitish: ${{ steps.commit.outputs.commit_long_sha }}
